### DISCUSSION TITLE
aws client 비활성화

### DISCUSSION THREAD

**Discussion by choisungwook** [INFP-Study/CIAT#219] [General]
# 문제
* aws sdk를 쓰면 EC2 정보를 읽는다. 이 프로젝트에서 사용하는 목적은 s3이므로 ec2정보를 설정하지 않아 오류가 발생한다.

# 해결방법
## VM옵션 추가
```java
-Dcom.amazonaws.sdk.disableEc2Metadata=true
```

## 로그레벨 설정
```
logging:
  level:
    com:      
      amazonaws:
        util:
          EC2MetadataUtils: error
```

# 참고자료
* [1] https://lemontia.tistory.com/1006
